# permissions for end users to view locusts.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: locust-viewer-role
rules:
- apiGroups:
  - locustload.cndev.io
  resources:
  - locusts
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - locustload.cndev.io
  resources:
  - locusts/status
  verbs:
  - get
