
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  creationTimestamp: null
  name: manager-role
rules:
- apiGroups:
  - apps
  resources:
  - deployments
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - autoscaling
  resources:
  - horizontalpodautoscaler
  verbs:
  - get
  - list
- apiGroups:
  - ""
  resources:
  - pods
  - service
  verbs:
  - get
  - list
- apiGroups:
  - locustload.cndev.io
  resources:
  - locusts
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - locustload.cndev.io
  resources:
  - locusts/finalizers
  verbs:
  - update
- apiGroups:
  - locustload.cndev.io
  resources:
  - locusts/status
  verbs:
  - get
  - patch
  - update
