apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  name: locusts.locustload.cndev.io
spec:
  group: locustload.cndev.io
  names:
    kind: Locust
    listKind: LocustList
    plural: locusts
    singular: locust
  scope: Namespaced
  subresources:
    status: {}
  validation:
    openAPIV3Schema:
      description: Locust is the Schema for the locusts API
      properties:
        apiVersion:
          description: 'APIVersion defines the versioned schema of this representation
            of an object. Servers should convert recognized schemas to the latest
            internal value, and may reject unrecognized values. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#resources'
          type: string
        kind:
          description: 'Kind is a string value representing the REST resource this
            object represents. Servers may infer this from the endpoint the client
            submits requests to. Cannot be updated. In CamelCase. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#types-kinds'
          type: string
        metadata:
          type: object
        spec:
          description: LocustSpec defines the desired state of Locust
          properties:
            hatchrate:
              description: HatchRate is the maximum number of users to simulate
              type: integer
            hosturl:
              description: HostURL is the url the loadtest is executed agains
              type: string
            image:
              description: Image is the container with locust files tests
              type: string
            slaves:
              description: Slaves is the number of worker instances
              format: int32
              type: integer
            users:
              description: Users is the maximum number of users to simulate
              type: integer
          required:
          - hosturl
          - image
          type: object
        status:
          description: LocustStatus defines the observed state of Locust
          properties:
            currentworkers:
              format: int32
              type: integer
          type: object
      type: object
  version: v1alpha1
  versions:
  - name: v1alpha1
    served: true
    storage: true
