build:
	docker build . -t amilaku/locust:v0.0.1

build-slim:
	docker build . -f Dockerfile.slim -t amilaku/locust:v0.0.1-slim

push:
	docker push amilaku/locust:v0.0.1

push-slim:
	docker push amilaku/locust:v0.0.1-slim